# as described here: https://www.reddit.com/r/neovim/comments/16p1e89/masonnvim_clangd_not_finding_header_files
#
# When it comes to finding the right paths:
#
# nix-locate
#   (mentioned here https://discourse.nixos.org/t/c-header-includes-in-nixos/17410)
#
# `gcc -print-prog-name=cc1plus` -v
#   to find header files
#   (as mentioned here: https://stackoverflow.com/questions/344317/where-does-gcc-look-for-c-and-c-header-files)

CompileFlags:

  Add: [ -I/nix/store/81awch8mhqanda1vy0c09bflgra4cxh0-glibc-2.40-66-dev/include ]

